### ISSUE TITLE
Do you have Viri's FL code by chance?

### ISSUE THREAD

**Issue by 0xDEADFED5** [Usualdosage/Legendary#82]
I had it ages ago not sure where I put it, but I'd like use it as a reference for a couple things if you or anybody else is willing to share

**Comment by Usualdosage** [comment]
If by "Viri's FL code" you mean the work that Viri and I both did on an open sourced ROM codebase, no. I don't have that.

**Comment by 0xDEADFED5** [comment]
sorry, no disrespect intended.  i was a drunken idiot when i first had my
bright idea, sorry for being a weirdo.

i'm porting some of the old FL code to Evennia for a local LLM project i've
been working on.  if that interests you at all (won't blame you if it
doesn't) then i'll send you an email when i've got it sorted out a bit more
